name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version upgrade'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major


jobs:
  publish:
    name: Publish Package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.bump }} --no-git-tag-version

      - name: Install dependencies
        run: npm install

      - name: Building Project
        run: npm run make

      - name: Setup Token
        run: echo "GITHUB_TOKEN=${{ secrets.PUBLISH_TOKEN }}" > .env

      - name: Publish project on github
        run: npm run publish

      - name: Publish Version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          git push origin --tags