name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version upgrade'
        required: true
        default: 'minor'
        type: choice
        options:
          - patch
          - minor
          - major


jobs:
  publish:
    name: Publish Package
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Configure Git
        run: |
          git config user.name "Kormtusor[bot]"
          git config user.email "lehericy.gautier@sfr.fr"

      - name: Authenticate with PAT
        run: git remote set-url origin https://x-access-token:${{ secrets.PUBLISH_TOKEN }}@github.com/${{ github.repository }}

      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.bump }} --no-git-tag-version

      - name: Install dependencies
        run: npm install

      - name: Setup Token
        run: echo "GITHUB_TOKEN=${{ secrets.PUBLISH_TOKEN }}" > .env

      - name: Publish project on github
        run: npm run publish -- --platform=win32

      - name: Publish Version
        run: |
          git add .
          git commit -m "feat(version): new version released"
          git push origin
          git push origin --tags